[package]
name = "vote-state"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.26.0"
bincode = "1.3.3"
serde = "1.0.138"
serde_derive = "1.0.103"
solana-program = "1.14.12"
