[features]
seeds = false
skip-lint = false

[programs.localnet]
stack_overflow_test = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/seg/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
slots_per_epoch = "64"
ticks_per_slot = 8

[workspace]
members = [
    "programs/stack-overflow-test",
]
exclude = ["programs/vote-state"]

